### PR TITLE
Symfony 4 compatibility attempt

### PR DESCRIPTION
**Pull request by pesektomas**
#149 Attempt for symfony4 compatibility. Discussion is welcome.

### CODE REVIEW

**Comment by 66Ton99** [comment]
It's OK as for me, but need to restore build on https://travis-ci.org/formapro/JsFormValidatorBundle before I would be able to merge it.
If you need some changes from my side please ask.

**Comment by pesektomas** [comment]
Ou, I have more problems with tests and build. But I will try to solved it.

**Comment by pesektomas** [comment]
Hello @66Ton99, we spent a lot of time with trying to fixed broken tests, but it is really hard. Some libraries already not exist (https://github.com/ptcong/php-image-uploader) and trying to run selenium is other story, ...

Finally, we tried write concept of new tests. We coverated javascript's constraints by unit tests and we writed new e2e test for checking complet functionality. For e2e test we used new project base in Tests folder builded on symfony 4.

I know that is not good way, but I really don't know how to fix broken old tests.

Could I ask you for your opinion on this solution?

**Comment by 66Ton99** [comment]
Looks great.
Thanks!

**Pull request merged**
