### PR TITLE
Check for child.tagName before using it in Resources/public/js/fp_js_validator.js

### PR DESCRIPTION
**Pull request by asentner**
Getting an error in the console:

```
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
```

### CODE REVIEW

**Comment by manuelj555** [comment]
+1

**Comment by manuelj555** [comment]
This is related to https://github.com/formapro/JsFormValidatorBundle/issues/66

**Comment by 66Ton99** [comment]
Please rebase it to master.

**Comment by asentner** [comment]
Done

**Pull request merged**
