### PR TITLE
Updates for Symfony 2.7

### PR DESCRIPTION
**Pull request by benr77**
Some simple updates for Symfony2.7 compatibility

### CODE REVIEW

**Comment by 66Ton99** [comment]
Looks like you need to rebase with master

**Comment by benr77** [comment]
Not quite sure what I'm doing but think I've sorted it - see #89

**Comment by 66Ton99** [comment]
May be everything is OK with PR it self but changes brake backward compatibility with previous version of Symfony and because of that I will not merge it, at list now. May be in next major version.

**Comment by robertfausk** [comment]
@66Ton99 What about creating a new major version for symfony 2.7 compatibility? Most of people are using 2.7 and therefore won't be able to use this bundle right now.

**Comment by benr77** [comment]
Yes, that's a great idea, plus could also remove any deprecation issues making it compatible with 2.7.x -> 3.x. Otherwise this same issue is going to come around again once people want to use 2.8 and above.

**Comment by 66Ton99** [comment]
@robertfausk I OK with it, but now I do not work with Symfony, so PRs are welcome

**Comment by robertfausk** [comment]
@66Ton99 Ok. 
So what do we need?
1. A new branch consisting of current master with name 1.2. From this branch fixes can still be applied for new tags v1.2.x
This branch is also already specifying the supported symfony versions in composer.json.
2. Needed changes for branch master:
2.1 update dependencies (symfony >=2.5.5) 
2.2 merge this PR
2.3 create UPGRADE.1.3.md
2.4 will result in new tag v1.3.0 when it reached a stable version

@benr77 Can you provide changes for points 2.1 and 2.4 in this PR?

**Pull request merged**
